# Generated by Django 4.0.1 on 2022-06-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_holder_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
