# Generated by Django 4.0.1 on 2022-06-11 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='number_of_cards',
        ),
        migrations.RemoveField(
            model_name='user',
            name='number_of_locks',
        ),
    ]
